kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prod-postgres-disk-pvc
  labels:
    app: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
